### ISSUE TITLE
Add support for {year}, {month}, {day}, {hour}, {minute}, {second} to note templates

### ISSUE THREAD

**Issue by renerocksai** [renerocksai/sublime_zk#49]
Makes it possible to form a pandoc header like this:

```yaml
---
title: {title}
author: My Name
date: {year}-{month}-{day}
tags: 
---
```

Consider the following, fields, too:

* `{human_day}`: 1st, 2nd, 3rd, 21st, 11th, ...
* `{human_month}`: January, February ...
* `{human_month_short}`: Jan, Feb, ...
